export const MOUSE_ENTER_ANIMATION = 'MOUSE_ENTER_ANIMATION';
export const MOUSE_LEAVE_ANIMATION = 'MOUSE_LEAVE_ANIMATION';
export const MOUSE_DOWN_ANIMATION = 'MOUSE_DOWN_ANIMATION';
export const MOUSE_GO_WHITE = 'MOUSE_GO_WHITE';
export const MOUSE_GO_BLACK = 'MOUSE_GO_BLACK';
//export const MOUSE_UP_ANIMATION = 'MOUSE_UP_ANIMATION';

export const MENU_HOME = 'MENU_HOME';
export const MENU_ABOUT = 'MENU_ABOUT';
export const MENU_WORK = 'MENU_WORK';
export const MENU_TOGGLE = 'MENU_TOGGLE';
