export const MOUSE_ENTER_ANIMATION = 'MOUSE_ENTER_ANIMATION';
export const MOUSE_LEAVE_ANIMATION = 'MOUSE_LEAVE_ANIMATION';
export const MOUSE_UP_ANIMATION = 'MOUSE_UP_ANIMATION';
export const MOUSE_DOWN_ANIMATION = 'MOUSE_DOWN_ANIMATION';

export const MENU_TOGGLE = 'MENU_TOGGLE';
